### PR TITLE
fix: using lipgloss tables instead of tablewriter

### LINKED ISSUE #617: tablewriter project archived without license
**Describe the bug**
Project is using a project that is archived by the author: https://github.com/caarlos0-graveyard/tablewriter
It also does not have a license listed in the repo

**Expected behavior**
Can the code be replaced with a different library that is supported?

**Environment (please complete the following information):**
 - OS: Linux
 - Version 0.7.6

**Additional context**

### PR DESCRIPTION
**Pull request by caarlos0**
closes #617

### CODE REVIEW

**Comment by roccotigger** [comment]
it looks like the tests are failing because they expect no border in the table.
does lipgloss support removing the boarders or does the expected values need to change to match?

File: pkg/ssh/cmd/token.go [hunk 1]
```diff
@@ -92,28 +92,25 @@ func TokenCommand() *cobra.Command {
...
-				[]string{"ID", "Name", "Created At", "Expires In"},
-				func(t proto.AccessToken) ([]string, error) {
-					expiresAt := "-"
-					if !t.ExpiresAt.IsZero() {
-						if now.After(t.ExpiresAt) {
-							expiresAt = "expired"
-						} else {
-							expiresAt = humanize.Time(t.ExpiresAt)
-						}
+			table := table.New().Headers("ID", "Name", "Created At", "Expires In")
```
Comment (roccotigger) [inline pkg/ssh/cmd/token.go:95]:
```suggestion
			table := table.New().Headers("ID", "Name", "Created At", "Expires In").Border(lipgloss.HiddenBorder())
```

File: pkg/ssh/cmd/webhooks.go [hunk 2]
```diff
@@ -60,28 +60,24 @@ func webhookListCommand() *cobra.Command {
...
-
-					row := []string{
-						strconv.FormatInt(h.ID, 10),
-						h.URL,
-						strings.Join(events, ","),
-						strconv.FormatBool(h.Active),
-						humanize.Time(h.CreatedAt),
-						humanize.Time(h.UpdatedAt),
-					}
+			table := table.New().Headers("ID", "URL", "Events", "Active", "Created At", "Updated At")
```
Comment (roccotigger) [inline pkg/ssh/cmd/webhooks.go:63]:
```suggestion
			table := table.New().Headers("ID", "URL", "Events", "Active", "Created At", "Updated At").Border(lipgloss.HiddenBorder())
```

File: pkg/ssh/cmd/webhooks.go [hunk 3]
```diff
@@ -290,24 +286,21 @@ func webhookDeliveriesListCommand() *cobra.Command {
...
-
-					return []string{
-						status,
-						d.ID.String(),
-						d.Event.String(),
-						humanize.Time(d.CreatedAt),
-					}, nil
-				},
-			)
+			table := table.New().Headers("Status", "ID", "Event", "Created At")
```
Comment (roccotigger) [inline pkg/ssh/cmd/webhooks.go:289]:
```suggestion
			table := table.New().Headers("Status", "ID", "Event", "Created At").Border(lipgloss.HiddenBorder())
```

**Review by roccotigger — COMMENTED** [review]
suggestions to have the border be hidden to match the test file expected output

**Comment by caarlos0** [comment]
> suggestions to have the border be hidden to match the test file expected output

i fixed the test... I think it looks better with the borders... 🤔

**Review by aymanbagabas — APPROVED** [review]
